#!/bin/bash
########################
### CONFIG GOES HERE ###
########################

SERVERNAME=example.com
WARNTHRESH=30
CRITTHRESH=10

########################

TEST=$(echo | openssl s_client -connect $SERVERNAME:443 -servername $SERVERNAME 2>/dev/null | openssl x509 -noout -dates)

crit ()
        {

        echo "CRITICAL"
        echo "Cert for $SERVERNAME will expire in less than $CRITTHRESH days!"
        exit 2

        }

warning ()
        {

        echo "WARNING"
        echo "Cert for $SERVERNAME will expire in less than $WARNTHRESH days!"
        exit 1

        }

good ()
        {

        echo "OK"
        echo "Cert for $SERVERNAME is valid, expires: $EXP, $CERT Days."

        }

main ()
        {

        MONTH=$(echo $TEST | grep "notAfter" | awk -F 'After=' '{print $2}' | awk -F ' ' '{print $1}')
        DAY=$(echo $TEST | grep "notAfter" | awk -F 'After=' '{print $2}' | awk -F ' ' '{print $2}')
        YEAR=$(echo $TEST | grep "notAfter" | awk -F 'After=' '{print $2}' | awk -F ' ' '{print $4}')
        YEARTODAY=$(date +%Y)
        
        if [[ $MONTH = Jan ]]; then
        NUMMONTH=1
else
        if [[ $MONTH = Feb ]]; then
                NUMMONTH=2
        else
                if [[ $MONTH = Mar ]]; then
                        NUMMONTH=3
                else
                        if [[ $MONTH = Apr ]]; then
                                NUMMONTH=4
                        else
                                if [[ $MONTH = May ]]; then
                                        NUMMONTH=5
                                else
                                        if [[ $MONTH = Jun ]]; then
                                                NUMMONTH=6
                                        else
                                                if [[ $MONTH = Jul ]]; then
                                                        NUMMONTH=7
                                                else
                                                        if [[ $MONTH = Aug ]]; then
                                                                NUMMONTH=8
                                                        else
                                                                if [[ $MONTH = Sep ]]; then
                                                                        NUMMONTH=9
                                                                else
                                                                        if [[ $MONTH = Oct ]]; then
                                                                                NUMMONTH=10
                                                                        else
                                                                                if [[ $MONTH = Nov ]]; then
                                                                                        NUMMONTH=11
                                                                                else
                                                                                        NUMMONTH=12
                                                                                fi
                                                                        fi
                                                                fi
                                                        fi
                                                fi
                                        fi
                                fi
                        fi
                fi
        fi
fi

EXP=$(echo "$NUMMONTH/$DAY/$YEAR")
CERT=$(echo $(( ($(date -d $EXP +%s) - $(date +%s)) / 86400 )))

if [[ $YEAR = $YEARTODAY ]]; then
        if [[ $CERT -le $WARNTHRESH ]]; then
                if [[ $CERT -le $CRITTHRESH ]]; then
                        crit;
                else
                        warning;
                fi
        else
                good;
        fi
fi

        }

main;
